export type MealCategory =
  | "petit-dejeuner"
  | "dejeuner"
  | "diner"
  | "collation";

export type RecipeTag =
  | "proteine"
  | "vegetarien"
  | "faible-calories"
  | "masse"
  | "seche";

export interface Recipe {
  id: string;
  title: string;
  category: MealCategory;
  tags: RecipeTag[];
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  time: number; // minutes
  image: string;
  ingredients: string[];
  steps: string[];
}

export const categoryLabels: Record<MealCategory, string> = {
  "petit-dejeuner": "Petit-déjeuner",
  dejeuner: "Déjeuner",
  diner: "Dîner",
  collation: "Collation",
};

export const tagLabels: Record<RecipeTag, string> = {
  proteine: "Riche en protéines",
  vegetarien: "Végétarien",
  "faible-calories": "Faible en calories",
  masse: "Prise de masse",
  seche: "Sèche",
};

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=75`;

export const recipes: Recipe[] = [
  {
    id: "bowl-proteine-avoine",
    title: "Porridge protéiné banane & beurre de cacahuète",
    category: "petit-dejeuner",
    tags: ["proteine", "vegetarien", "masse"],
    kcal: 540,
    protein: 38,
    carbs: 62,
    fat: 16,
    time: 10,
    image: img("photo-1484723091739-30a097e8f929"),
    ingredients: [
      "80 g de flocons d'avoine",
      "1 scoop (30 g) de whey vanille",
      "250 ml de lait demi-écrémé",
      "1 banane",
      "15 g de beurre de cacahuète",
      "1 pincée de cannelle",
    ],
    steps: [
      "Faites chauffer les flocons d'avoine avec le lait 3 à 4 minutes à feu doux.",
      "Hors du feu, incorporez la whey en mélangeant énergiquement.",
      "Ajoutez la banane en rondelles, le beurre de cacahuète et la cannelle.",
    ],
  },
  {
    id: "toast-avocat-oeuf",
    title: "Toast complet avocat & œufs pochés",
    category: "petit-dejeuner",
    tags: ["proteine", "vegetarien"],
    kcal: 420,
    protein: 22,
    carbs: 34,
    fat: 22,
    time: 15,
    image: img("photo-1525351484163-7529414344d8"),
    ingredients: [
      "2 tranches de pain complet",
      "1/2 avocat mûr",
      "2 œufs",
      "Jus de citron, piment doux",
      "Sel, poivre",
    ],
    steps: [
      "Toastez le pain et écrasez l'avocat avec le citron, le sel et le poivre.",
      "Pochez les œufs 3 minutes dans une eau frémissante vinaigrée.",
      "Dressez l'avocat sur les toasts, déposez les œufs et le piment doux.",
    ],
  },
  {
    id: "pancakes-proteines",
    title: "Pancakes protéinés aux myrtilles",
    category: "petit-dejeuner",
    tags: ["proteine", "vegetarien", "masse"],
    kcal: 480,
    protein: 35,
    carbs: 55,
    fat: 12,
    time: 20,
    image: img("photo-1493770348161-369560ae357d"),
    ingredients: [
      "60 g de flocons d'avoine mixés",
      "1 scoop de whey vanille",
      "2 œufs",
      "100 g de fromage blanc 0 %",
      "80 g de myrtilles",
      "1/2 sachet de levure",
    ],
    steps: [
      "Mixez tous les ingrédients sauf les myrtilles jusqu'à obtenir une pâte lisse.",
      "Incorporez les myrtilles délicatement.",
      "Cuisez 2 minutes par face dans une poêle antiadhésive légèrement huilée.",
    ],
  },
  {
    id: "skyr-granola",
    title: "Bol de skyr, granola maison & fruits rouges",
    category: "petit-dejeuner",
    tags: ["proteine", "vegetarien", "faible-calories", "seche"],
    kcal: 320,
    protein: 28,
    carbs: 38,
    fat: 7,
    time: 5,
    image: img("photo-1488477181946-6428a0291777"),
    ingredients: [
      "250 g de skyr nature",
      "30 g de granola",
      "100 g de fruits rouges",
      "1 c. à café de miel",
    ],
    steps: [
      "Versez le skyr dans un bol.",
      "Ajoutez le granola, les fruits rouges et le filet de miel.",
    ],
  },
  {
    id: "omelette-legumes",
    title: "Omelette aux légumes du soleil",
    category: "petit-dejeuner",
    tags: ["proteine", "vegetarien", "faible-calories", "seche"],
    kcal: 290,
    protein: 24,
    carbs: 9,
    fat: 18,
    time: 12,
    image: img("photo-1482049016688-2d3e1b311543"),
    ingredients: [
      "3 œufs",
      "1/2 poivron rouge",
      "1/2 courgette",
      "30 g de feta",
      "Basilic frais, huile d'olive",
    ],
    steps: [
      "Faites revenir les légumes en dés 5 minutes dans un filet d'huile d'olive.",
      "Versez les œufs battus, salez, poivrez.",
      "Émiettez la feta, cuisez à feu doux et parsemez de basilic.",
    ],
  },
  {
    id: "smoothie-vert",
    title: "Smoothie vert épinards, mangue & protéines",
    category: "petit-dejeuner",
    tags: ["vegetarien", "faible-calories", "seche"],
    kcal: 260,
    protein: 22,
    carbs: 34,
    fat: 4,
    time: 5,
    image: img("photo-1511690743698-d9d85f2fbf38"),
    ingredients: [
      "1 poignée d'épinards frais",
      "150 g de mangue surgelée",
      "1 scoop de protéine végétale vanille",
      "250 ml d'eau de coco",
      "Jus d'1/2 citron vert",
    ],
    steps: [
      "Placez tous les ingrédients dans un blender.",
      "Mixez 45 secondes jusqu'à une texture lisse et servez bien frais.",
    ],
  },
  {
    id: "poulet-riz-brocoli",
    title: "Poulet grillé, riz basmati & brocoli vapeur",
    category: "dejeuner",
    tags: ["proteine", "masse"],
    kcal: 620,
    protein: 52,
    carbs: 68,
    fat: 12,
    time: 25,
    image: img("photo-1432139555190-58524dae6a55"),
    ingredients: [
      "180 g de filet de poulet",
      "90 g de riz basmati (cru)",
      "200 g de brocoli",
      "Paprika fumé, ail, huile d'olive",
    ],
    steps: [
      "Cuisez le riz selon les indications du paquet.",
      "Grillez le poulet mariné au paprika et à l'ail 5 à 6 minutes par face.",
      "Cuisez le brocoli 6 minutes à la vapeur et dressez avec un filet d'huile d'olive.",
    ],
  },
  {
    id: "buddha-bowl",
    title: "Buddha bowl quinoa, pois chiches & avocat",
    category: "dejeuner",
    tags: ["vegetarien", "proteine"],
    kcal: 560,
    protein: 24,
    carbs: 62,
    fat: 24,
    time: 20,
    image: img("photo-1512621776951-a57141f2eefd"),
    ingredients: [
      "80 g de quinoa (cru)",
      "120 g de pois chiches cuits",
      "1/2 avocat",
      "1 carotte râpée",
      "80 g de chou rouge émincé",
      "Sauce tahini-citron",
    ],
    steps: [
      "Cuisez le quinoa 12 minutes puis laissez-le refroidir.",
      "Rôtissez les pois chiches au paprika 10 minutes à la poêle.",
      "Assemblez le bowl et nappez de sauce tahini-citron.",
    ],
  },
  {
    id: "saumon-patate-douce",
    title: "Pavé de saumon rôti & purée de patate douce",
    category: "dejeuner",
    tags: ["proteine", "masse"],
    kcal: 590,
    protein: 38,
    carbs: 48,
    fat: 26,
    time: 30,
    image: img("photo-1467003909585-2f8a72700288"),
    ingredients: [
      "150 g de pavé de saumon",
      "250 g de patate douce",
      "100 g d'épinards frais",
      "Citron, aneth, huile d'olive",
    ],
    steps: [
      "Rôtissez le saumon 12 minutes au four à 200 °C avec citron et aneth.",
      "Cuisez la patate douce à l'eau puis écrasez-la en purée.",
      "Faites tomber les épinards à la poêle 2 minutes et dressez.",
    ],
  },
  {
    id: "salade-cesar-light",
    title: "Salade César légère au poulet grillé",
    category: "dejeuner",
    tags: ["proteine", "faible-calories", "seche"],
    kcal: 380,
    protein: 40,
    carbs: 18,
    fat: 16,
    time: 15,
    image: img("photo-1546069901-ba9599a7e63c"),
    ingredients: [
      "150 g de filet de poulet",
      "1 cœur de romaine",
      "20 g de parmesan",
      "30 g de croûtons complets",
      "Sauce yaourt-moutarde-anchois",
    ],
    steps: [
      "Grillez le poulet et coupez-le en lamelles.",
      "Mélangez la romaine avec la sauce légère.",
      "Ajoutez poulet, croûtons et copeaux de parmesan.",
    ],
  },
  {
    id: "wrap-thon",
    title: "Wrap complet au thon & légumes croquants",
    category: "dejeuner",
    tags: ["proteine", "faible-calories", "seche"],
    kcal: 410,
    protein: 34,
    carbs: 42,
    fat: 12,
    time: 10,
    image: img("photo-1540189549336-e6e99c3679fe"),
    ingredients: [
      "1 tortilla complète",
      "120 g de thon au naturel",
      "2 c. à soupe de fromage blanc",
      "1/4 de concombre, 1 tomate",
      "Salade, moutarde",
    ],
    steps: [
      "Mélangez le thon avec le fromage blanc et la moutarde.",
      "Garnissez la tortilla de salade, légumes et thon.",
      "Roulez serré et coupez en deux.",
    ],
  },
  {
    id: "pates-completes-dinde",
    title: "Pâtes complètes, émincé de dinde & sauce tomate",
    category: "dejeuner",
    tags: ["proteine", "masse"],
    kcal: 640,
    protein: 48,
    carbs: 78,
    fat: 12,
    time: 25,
    image: img("photo-1473093295043-cdd812d0e601"),
    ingredients: [
      "100 g de pâtes complètes (crues)",
      "150 g d'émincé de dinde",
      "200 g de sauce tomate nature",
      "1 oignon, ail, basilic",
      "20 g de parmesan",
    ],
    steps: [
      "Cuisez les pâtes al dente.",
      "Faites revenir l'oignon puis la dinde 6 à 7 minutes, ajoutez la sauce tomate.",
      "Mélangez avec les pâtes, parsemez de basilic et de parmesan.",
    ],
  },
  {
    id: "poke-bowl-saumon",
    title: "Poke bowl saumon, riz vinaigré & edamame",
    category: "dejeuner",
    tags: ["proteine"],
    kcal: 550,
    protein: 32,
    carbs: 64,
    fat: 18,
    time: 20,
    image: img("photo-1546069901-ba9599a7e63c"),
    ingredients: [
      "120 g de saumon frais en dés",
      "80 g de riz à sushi (cru)",
      "60 g d'edamame",
      "1/4 de mangue, 1/4 d'avocat",
      "Sauce soja, sésame, gingembre",
    ],
    steps: [
      "Cuisez le riz puis assaisonnez-le de vinaigre de riz.",
      "Faites mariner le saumon dans la sauce soja et le gingembre.",
      "Dressez le bowl et parsemez de graines de sésame.",
    ],
  },
  {
    id: "boeuf-saute-legumes",
    title: "Bœuf sauté au wok, légumes croquants & riz",
    category: "diner",
    tags: ["proteine", "masse"],
    kcal: 610,
    protein: 44,
    carbs: 58,
    fat: 20,
    time: 20,
    image: img("photo-1512058564366-18510be2db19"),
    ingredients: [
      "150 g de bœuf (rumsteck) émincé",
      "80 g de riz jasmin (cru)",
      "1 poivron, 1 carotte, 100 g de brocoli",
      "Sauce soja, ail, gingembre, sésame",
    ],
    steps: [
      "Saisissez le bœuf 2 minutes à feu vif au wok, réservez.",
      "Sautez les légumes 5 minutes, ajoutez ail et gingembre.",
      "Remettez le bœuf, déglacez à la sauce soja et servez sur le riz.",
    ],
  },
  {
    id: "curry-lentilles",
    title: "Curry de lentilles corail au lait de coco",
    category: "diner",
    tags: ["vegetarien", "proteine"],
    kcal: 520,
    protein: 24,
    carbs: 66,
    fat: 18,
    time: 25,
    image: img("photo-1455619452474-d2be8b1e70cd"),
    ingredients: [
      "120 g de lentilles corail",
      "150 ml de lait de coco léger",
      "200 g de tomates concassées",
      "1 oignon, curry, curcuma",
      "Coriandre fraîche",
    ],
    steps: [
      "Faites revenir l'oignon avec les épices 2 minutes.",
      "Ajoutez lentilles, tomates et 250 ml d'eau, cuisez 15 minutes.",
      "Incorporez le lait de coco, laissez épaissir et parsemez de coriandre.",
    ],
  },
  {
    id: "cabillaud-legumes-rotis",
    title: "Dos de cabillaud & légumes rôtis au thym",
    category: "diner",
    tags: ["proteine", "faible-calories", "seche"],
    kcal: 340,
    protein: 36,
    carbs: 28,
    fat: 8,
    time: 30,
    image: img("photo-1504674900247-0877df9cc836"),
    ingredients: [
      "160 g de dos de cabillaud",
      "1 courgette, 1 poivron, 150 g de tomates cerises",
      "Thym, citron, huile d'olive",
    ],
    steps: [
      "Rôtissez les légumes 20 minutes au four à 200 °C.",
      "Ajoutez le cabillaud sur la plaque, citron et thym, 10 minutes de plus.",
      "Servez avec un filet d'huile d'olive crue.",
    ],
  },
  {
    id: "soupe-detox",
    title: "Velouté vert courgette, épinards & pois",
    category: "diner",
    tags: ["vegetarien", "faible-calories", "seche"],
    kcal: 220,
    protein: 12,
    carbs: 26,
    fat: 8,
    time: 25,
    image: img("photo-1547592180-85f173990554"),
    ingredients: [
      "1 courgette",
      "100 g d'épinards",
      "100 g de petits pois",
      "1 bouillon de légumes",
      "1 c. à soupe de crème légère",
    ],
    steps: [
      "Cuisez les légumes 15 minutes dans le bouillon.",
      "Mixez finement avec la crème.",
      "Rectifiez l'assaisonnement et servez bien chaud.",
    ],
  },
  {
    id: "chili-sin-carne",
    title: "Chili sin carne aux haricots rouges",
    category: "diner",
    tags: ["vegetarien", "proteine", "faible-calories"],
    kcal: 430,
    protein: 22,
    carbs: 62,
    fat: 10,
    time: 30,
    image: img("photo-1498837167922-ddd27525d352"),
    ingredients: [
      "200 g de haricots rouges cuits",
      "100 g de maïs",
      "200 g de tomates concassées",
      "1 oignon, cumin, paprika fumé",
      "60 g de riz complet (cru)",
    ],
    steps: [
      "Faites revenir l'oignon avec les épices.",
      "Ajoutez tomates, haricots et maïs, laissez mijoter 20 minutes.",
      "Servez sur le riz complet avec de la coriandre.",
    ],
  },
  {
    id: "brochettes-poulet",
    title: "Brochettes de poulet marinées & quinoa citronné",
    category: "diner",
    tags: ["proteine", "seche"],
    kcal: 470,
    protein: 45,
    carbs: 44,
    fat: 12,
    time: 25,
    image: img("photo-1555939594-58d7cb561ad1"),
    ingredients: [
      "160 g de filet de poulet en cubes",
      "70 g de quinoa (cru)",
      "1 poivron, 1/2 oignon rouge",
      "Yaourt, citron, paprika, origan",
    ],
    steps: [
      "Faites mariner le poulet 15 minutes dans le yaourt citronné épicé.",
      "Montez les brochettes en alternant poulet et légumes.",
      "Grillez 12 minutes en tournant et servez sur le quinoa.",
    ],
  },
  {
    id: "steak-frites-patate-douce",
    title: "Steak grillé & frites de patate douce au four",
    category: "diner",
    tags: ["proteine", "masse"],
    kcal: 650,
    protein: 42,
    carbs: 52,
    fat: 28,
    time: 35,
    image: img("photo-1544025162-d76694265947"),
    ingredients: [
      "160 g de steak de bœuf",
      "300 g de patate douce",
      "Salade verte",
      "Paprika, huile d'olive, herbes de Provence",
    ],
    steps: [
      "Coupez la patate douce en frites, enrobez d'huile et de paprika, 25 minutes au four à 210 °C.",
      "Grillez le steak selon la cuisson souhaitée.",
      "Servez avec la salade verte assaisonnée.",
    ],
  },
  {
    id: "bowl-cottage",
    title: "Bowl de cottage cheese, concombre & noix",
    category: "collation",
    tags: ["proteine", "vegetarien", "faible-calories", "seche"],
    kcal: 240,
    protein: 24,
    carbs: 10,
    fat: 12,
    time: 5,
    image: img("photo-1490645935967-10de6ba17061"),
    ingredients: [
      "200 g de cottage cheese",
      "1/4 de concombre",
      "15 g de noix",
      "Ciboulette, poivre",
    ],
    steps: [
      "Versez le cottage cheese dans un bol.",
      "Ajoutez le concombre en dés, les noix concassées et la ciboulette.",
    ],
  },
  {
    id: "energy-balls",
    title: "Energy balls avoine, dattes & cacao",
    category: "collation",
    tags: ["vegetarien", "masse"],
    kcal: 310,
    protein: 10,
    carbs: 42,
    fat: 12,
    time: 15,
    image: img("photo-1466637574441-749b8f19452f"),
    ingredients: [
      "100 g de dattes dénoyautées",
      "60 g de flocons d'avoine",
      "20 g de cacao non sucré",
      "20 g d'amandes",
      "1 c. à soupe de beurre d'amande",
    ],
    steps: [
      "Mixez tous les ingrédients jusqu'à obtenir une pâte collante.",
      "Formez 8 boules et réservez 30 minutes au frais.",
    ],
  },
  {
    id: "shake-post-training",
    title: "Shake post-training banane & flocons",
    category: "collation",
    tags: ["proteine", "vegetarien", "masse"],
    kcal: 390,
    protein: 32,
    carbs: 52,
    fat: 6,
    time: 5,
    image: img("photo-1553530666-ba11a7da3888"),
    ingredients: [
      "1 scoop de whey chocolat",
      "1 banane",
      "40 g de flocons d'avoine",
      "300 ml de lait d'amande",
      "Glaçons",
    ],
    steps: [
      "Placez tous les ingrédients dans un blender.",
      "Mixez 30 secondes et consommez dans l'heure qui suit la séance.",
    ],
  },
  {
    id: "toast-ricotta-miel",
    title: "Toast ricotta, miel & amandes torréfiées",
    category: "collation",
    tags: ["vegetarien"],
    kcal: 280,
    protein: 12,
    carbs: 32,
    fat: 12,
    time: 8,
    image: img("photo-1565958011703-44f9829ba187"),
    ingredients: [
      "1 tranche de pain aux céréales",
      "50 g de ricotta",
      "1 c. à café de miel",
      "10 g d'amandes effilées",
    ],
    steps: [
      "Toastez le pain et torréfiez les amandes à sec 2 minutes.",
      "Tartinez la ricotta, ajoutez le miel et les amandes.",
    ],
  },
];
